### ISSUE TITLE
Falta do "#" no href do botão de voltar para o topo

### ISSUE THREAD

**Issue by juanozorio** [marcosoliveira253/NOVO-PORTFOLIO#1]
Olá!

Encontrei seu post no linkedin e dei uma olhada no seu portifólio, está muito bom! Porém a falta do "#" no atributo href está fazendo a página recarregar novamente, removendo este problema, a experiência do usuário irá melhorar.

`<a rel="noreferrer" href="" title="Voltar ao topo da página"><i class="fa-solid fa-circle-up"></i></a>`

**Comment by marcosoliveira253** [comment]
Eu coloquei abaixo do footer.  Pois já havia colocado no portfólio anterior.
Mais valeu pela dica.👍 Obrigado.

**Comment by marcosoliveira253** [comment]
<footer>
      <div class="footer">
        <p>
        &copy; Marcos Oliveira - 2023 - Todos os direitos reservados.
        </p>

      </div>
    </footer>
    <a rel="noreferrer" href="" title="Voltar ao topo da página"><i class="fa-solid fa-circle-up"></i></a> 
</body>

**Comment by marcosoliveira253** [comment]
Entendi agora.kkkk Vou colocar.
